name: 'Discord Notification'
description: 'Sends a rich, customizable Discord notification for GitHub Actions events.'
author: 'taroj1205'

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  webhook_url:
    description: 'The Discord webhook URL.'
    required: true
  color:
    description: 'The decimal color of the embed.'
    required: false
    default: '3447003' # Blue
  title:
    description: 'The title of the embed.'
    required: true
  description:
    description: 'The description of the embed. Supports GitHub-flavored markdown.'
    required: true
  description_max_length:
    description: 'The maximum number of characters for the description. The description will be truncated with an ellipsis (...) if it exceeds this limit.'
    required: false
  url:
    description: 'The URL the embed title links to.'
    required: false
  image_url:
    description: 'The URL of the main image in the embed.'
    required: false
  author_name:
    description: 'The name of the embed author.'
    required: false
  author_url:
    description: 'The URL of the embed author.'
    required: false
  author_icon_url:
    description: 'The icon URL of the embed author.'
    required: false
  button_label:
    description: "The label for the button. The button will only be shown if a URL is also provided."
    required: false
    default: "View Details"
  branch_info:
    description: 'The branch information to display in a field (e.g., `head` -> `base`).'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Send Discord Notification
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/send-notification.sh
        ${{ github.action_path }}/send-notification.sh
      env:
        INPUT_WEBHOOK_URL: ${{ inputs.webhook_url }}
        INPUT_COLOR: ${{ inputs.color }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
        INPUT_DESCRIPTION_MAX_LENGTH: ${{ inputs.description_max_length }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_IMAGE_URL: ${{ inputs.image_url }}
        INPUT_AUTHOR_NAME: ${{ inputs.author_name }}
        INPUT_AUTHOR_URL: ${{ inputs.author_url }}
        INPUT_AUTHOR_ICON_URL: ${{ inputs.author_icon_url }}
        INPUT_BUTTON_LABEL: ${{ inputs.button_label }}
        INPUT_BRANCH_INFO: ${{ inputs.branch_info }} 