name: 'Send Discord Notification'
description: 'Constructs and sends a rich embed notification to a Discord webhook.'

inputs:
  webhook_url:
    description: 'The Discord webhook URL.'
    required: true
  color:
    description: 'The color of the embed.'
    required: true
  title:
    description: 'The title of the embed.'
    required: true
  description:
    description: 'The description of the embed.'
    required: true
  url:
    description: 'The URL the embed title links to.'
    required: true
  image_url:
    description: 'The URL of the main image in the embed.'
    required: false
  author_name:
    description: 'The name of the embed author.'
    required: true
  author_url:
    description: 'The URL of the embed author.'
    required: true
  author_icon_url:
    description: 'The icon URL of the embed author.'
    required: true
  button_label:
    description: "The label for the button"
    required: true
    default: "View Pull Request"
  branch_info:
    description: 'The branch information (e.g., `head` -> `base`).'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Make entrypoint script executable
      shell: bash
      run: chmod +x .github/actions/send-notification/entrypoint.sh

    - name: Send Discord Notification
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh
      env:
        INPUT_WEBHOOK_URL: ${{ inputs.webhook_url }}
        INPUT_COLOR: ${{ inputs.color }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_IMAGE_URL: ${{ inputs.image_url }}
        INPUT_AUTHOR_NAME: ${{ inputs.author_name }}
        INPUT_AUTHOR_URL: ${{ inputs.author_url }}
        INPUT_AUTHOR_ICON_URL: ${{ inputs.author_icon_url }}
        INPUT_BUTTON_LABEL: ${{ inputs.button_label }}
        INPUT_BRANCH_INFO: ${{ inputs.branch_info }} 