name: Pull Request Notifications

on:
  pull_request:
    types: [opened, reopened, closed, ready_for_review]

jobs:
  notify_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send "New Pull Request" Notification
        if: github.event.pull_request.draft == false && (github.event.action == 'opened' || github.event.action == 'reopened')
        run: |
          cat <<EOF > payload.json
          {
            "embeds": [
              {
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "title": "New Pull Request: ${{ github.event.pull_request.title }}",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 3447003
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "View Pull Request",
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
          EOF
          curl -X POST -H "Content-Type: application/json" -d @payload.json ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send "Ready for Review" Notification
        if: github.event.action == 'ready_for_review'
        run: |
          cat <<EOF > payload.json
          {
            "embeds": [
              {
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "title": "Ready for Review: ${{ github.event.pull_request.title }}",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 15105570
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "Review Pull Request",
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
          EOF
          curl -X POST -H "Content-Type: application/json" -d @payload.json ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Send "Pull Request Merged" Notification
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          cat <<EOF > payload.json
          {
            "embeds": [
              {
                "author": {
                  "name": "${{ github.event.pull_request.merged_by.login || github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.merged_by.html_url || github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.merged_by.avatar_url || github.event.pull_request.user.avatar_url }}"
                },
                "title": "Pull Request Merged: ${{ github.event.pull_request.title }}",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 5763719
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "View Merged Pull Request",
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }
          EOF
          curl -X POST -H "Content-Type: application/json" -d @payload.json ${{ secrets.DISCORD_WEBHOOK_URL }}
