name: Pull Request Notifications

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification on PR Opened or Ready for Review
        if: github.event.pull_request.draft == false && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'ready_for_review')
        run: |
          # Using printf to handle newlines correctly and truncate the description.
          DESCRIPTION=$(printf "**%s** submitted a pull request for review.\n\n%s" "${{ github.event.pull_request.user.login }}" "${{ github.event.pull_request.body }}" | head -c 4000)

          JSON_PAYLOAD=$(jq -n \
            --arg title "PR Ready for Review: ${{ github.event.pull_request.title }}" \
            --arg description "$DESCRIPTION" \
            --arg url "${{ github.event.pull_request.html_url }}" \
            --argjson color 3447003 \
            --arg author_name "${{ github.event.pull_request.user.login }}" \
            --arg author_url "${{ github.event.pull_request.user.html_url }}" \
            --arg author_icon_url "${{ github.event.pull_request.user.avatar_url }}" \
            --arg head_ref "${{ github.event.pull_request.head.ref }}" \
            --arg base_ref "${{ github.event.pull_request.base.ref }}" \
            '{
              "embeds": [
                {
                  "title": $title,
                  "description": $description,
                  "url": $url,
                  "color": $color,
                  "author": { "name": $author_name, "url": $author_url, "icon_url": $author_icon_url },
                  "thumbnail": { "url": $author_icon_url },
                  "fields": [
                    { "name": "Branch", "value": "`\($head_ref)` -> `\($base_ref)`", "inline": false }
                  ]
                }
              ],
              "components": [
                {
                  "type": 1,
                  "components": [
                    { "type": 2, "label": "View Pull Request", "style": 5, "url": $url }
                  ]
                }
              ]
            }')

          curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "${{ secrets.DISCORD_WEBHOOK_URL }}?with_components=true"

      - name: Send notification on PR Merged
        if: github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "PR Merged: ${{ github.event.pull_request.title }}",
                "description": "The pull request was merged by **${{ github.event.pull_request.merged_by.login }}**.",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 3066993,
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "thumbnail": { "url": "${{ github.event.pull_request.user.avatar_url }}" }
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "label": "View Merged PR",
                    "style": 5,
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}?with_components=true"

      - name: Send notification on PR Closed
        if: github.event.action == 'closed' && github.event.pull_request.merged == false
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
            "embeds": [
              {
                "title": "PR Closed: ${{ github.event.pull_request.title }}",
                "description": "The pull request was closed without merging.",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 15158332,
                "author": {
                  "name": "${{ github.event.pull_request.user.login }}",
                  "url": "${{ github.event.pull_request.user.html_url }}",
                  "icon_url": "${{ github.event.pull_request.user.avatar_url }}"
                },
                "thumbnail": { "url": "${{ github.event.pull_request.user.avatar_url }}" }
              }
            ],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "label": "View Closed PR",
                    "style": 5,
                    "url": "${{ github.event.pull_request.html_url }}"
                  }
                ]
              }
            ]
          }' \
          "${{ secrets.DISCORD_WEBHOOK_URL }}?with_components=true"
